# Generated by Django 4.0.4 on 2022-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='false_answer_1',
            field=models.CharField(max_length=1027, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='false_answer_2',
            field=models.CharField(max_length=1027, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='false_answer_3',
            field=models.CharField(max_length=1027, null=True),
        ),
    ]
